name: bestow_data_main
description: Data implementation for bestow
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.4.0-282.3.beta"

dependencies:
  bestow_data:
  fpdart:
    git:
      url: https://github.com/SandroMaglione/fpdart
      ref: effect-refactor
      path: packages/fpdart
  freezed_annotation:
  meta:
  objectbox: ^4.0.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed:
  mocktail: ^1.0.3
  objectbox_generator: ^4.0.0
  riverpod_generator: ^2.4.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0


index_generator:
  exclude:
    - '**.g.dart'
  # Define the paths of the folders in which to generate the index files
  indexes:
    - path: lib/src/model

