// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/model/container/allocation/container_allocation.dart';
import 'src/model/container/container.dart';
import 'src/model/containment/containment.dart';
import 'src/model/image/image.dart';
import 'src/model/item/item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 9190919246797820888),
      name: 'ContainerImpl',
      lastPropertyId: const obx_int.IdUid(2, 5471802401770367182),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5320174672383884938),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5471802401770367182),
            name: 'containerKeyId',
            type: 11,
            flags: 552,
            indexId: const obx_int.IdUid(2, 4222243906182180953),
            relationTarget: 'ContainerKey')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 138617536353866379),
      name: 'ContainerKey',
      lastPropertyId: const obx_int.IdUid(5, 2362620040545378201),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7170388006748374099),
            name: 'number',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8941224255903576230),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5269665106346671635),
            name: 'refValue',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 3390060962605601122)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7971285564765932377),
            name: 'kindValue',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2362620040545378201),
            name: 'sizeValue',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 7584494430530453985),
      name: 'ItemImpl',
      lastPropertyId: const obx_int.IdUid(3, 8157615837710123094),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1549805612462743546),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1130233744611876090),
            name: 'keyId',
            type: 11,
            flags: 552,
            indexId: const obx_int.IdUid(4, 8892035720976978716),
            relationTarget: 'ItemKey'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8157615837710123094),
            name: 'imageToOneId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 5623137823168338711),
            relationTarget: 'ImageImpl')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 8093215439518371364),
      name: 'ItemKey',
      lastPropertyId: const obx_int.IdUid(2, 4030846401022834245),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4977205528993016316),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4030846401022834245),
            name: 'refData',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(6, 8959376247652277815))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 8435266954701970158),
      name: 'ContainerAllocationImpl',
      lastPropertyId: const obx_int.IdUid(5, 3755082164854801840),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8207793799000157109),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 755204125409317692),
            name: 'start',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2013961933570842091),
            name: 'fixedDisplayLength',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7868095781228007391),
            name: 'containerTypeUid',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3755082164854801840),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(7, 2851303846538118445))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 167306156845435140),
      name: 'ImageImpl',
      lastPropertyId: const obx_int.IdUid(5, 5380814056965852521),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7759260328745736261),
            name: 'itemToOneId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 5022835796626166426),
            relationTarget: 'ItemImpl'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 264707604461775807),
            name: 'refData',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(9, 3981732054058593780)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4620269097939630006),
            name: 'token',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5380814056965852521),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 8679458422601398496),
      name: 'ContainmentImpl',
      lastPropertyId: const obx_int.IdUid(1, 8238810890270604880),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8238810890270604880),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(9, 8679458422601398496),
      lastIndexId: const obx_int.IdUid(9, 3981732054058593780),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [3773422052721744386, 5694165611361444865],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        3843071922204309375,
        8943971859390874752,
        6716990357721271012,
        2158182812673860454,
        4127790479408864688,
        7796725037392309745,
        3531835921916943517
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ContainerImpl: obx_int.EntityDefinition<ContainerImpl>(
        model: _entities[0],
        toOneRelations: (ContainerImpl object) => [object.containerKey],
        toManyRelations: (ContainerImpl object) => {},
        getId: (ContainerImpl object) => object.id,
        setId: (ContainerImpl object, int id) {
          object.id = id;
        },
        objectToFB: (ContainerImpl object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.containerKey.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = ContainerImpl(id: idParam);
          object.containerKey.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.containerKey.attach(store);
          return object;
        }),
    ContainerKey: obx_int.EntityDefinition<ContainerKey>(
        model: _entities[1],
        toOneRelations: (ContainerKey object) => [],
        toManyRelations: (ContainerKey object) => {},
        getId: (ContainerKey object) => object.id,
        setId: (ContainerKey object, int id) {
          object.id = id;
        },
        objectToFB: (ContainerKey object, fb.Builder fbb) {
          final refValueOffset = fbb.writeString(object.refValue);
          fbb.startTable(6);
          fbb.addInt64(0, object.number);
          fbb.addInt64(1, object.id);
          fbb.addOffset(2, refValueOffset);
          fbb.addInt64(3, object.kindValue);
          fbb.addInt64(4, object.sizeValue);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refValueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final kindValueParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final sizeValueParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final numberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final object = ContainerKey(
              refValue: refValueParam,
              kindValue: kindValueParam,
              sizeValue: sizeValueParam,
              number: numberParam,
              id: idParam);

          return object;
        }),
    ItemImpl: obx_int.EntityDefinition<ItemImpl>(
        model: _entities[2],
        toOneRelations: (ItemImpl object) => [object.key, object.imageToOne],
        toManyRelations: (ItemImpl object) => {},
        getId: (ItemImpl object) => object.id,
        setId: (ItemImpl object, int id) {
          object.id = id;
        },
        objectToFB: (ItemImpl object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.key.targetId);
          fbb.addInt64(2, object.imageToOne.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = ItemImpl(id: idParam);
          object.key.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.key.attach(store);
          object.imageToOne.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.imageToOne.attach(store);
          return object;
        }),
    ItemKey: obx_int.EntityDefinition<ItemKey>(
        model: _entities[3],
        toOneRelations: (ItemKey object) => [],
        toManyRelations: (ItemKey object) => {},
        getId: (ItemKey object) => object.id,
        setId: (ItemKey object, int id) {
          object.id = id;
        },
        objectToFB: (ItemKey object, fb.Builder fbb) {
          final refDataOffset = fbb.writeString(object.refData);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, refDataOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refDataParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = ItemKey(refData: refDataParam, id: idParam);

          return object;
        }),
    ContainerAllocationImpl: obx_int.EntityDefinition<ContainerAllocationImpl>(
        model: _entities[4],
        toOneRelations: (ContainerAllocationImpl object) => [],
        toManyRelations: (ContainerAllocationImpl object) => {},
        getId: (ContainerAllocationImpl object) => object.id,
        setId: (ContainerAllocationImpl object, int id) {
          object.id = id;
        },
        objectToFB: (ContainerAllocationImpl object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.start);
          fbb.addInt64(2, object.fixedDisplayLength);
          fbb.addInt64(3, object.containerTypeUid);
          fbb.addOffset(4, uidOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final containerTypeUidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final startParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final fixedDisplayLengthParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = ContainerAllocationImpl(
              containerTypeUidParam, startParam, fixedDisplayLengthParam,
              uid: uidParam, id: idParam);

          return object;
        }),
    ImageImpl: obx_int.EntityDefinition<ImageImpl>(
        model: _entities[5],
        toOneRelations: (ImageImpl object) => [object.itemToOne],
        toManyRelations: (ImageImpl object) => {},
        getId: (ImageImpl object) => object.id,
        setId: (ImageImpl object, int id) {
          object.id = id;
        },
        objectToFB: (ImageImpl object, fb.Builder fbb) {
          final refDataOffset = fbb.writeString(object.refData);
          final tokenOffset = fbb.writeString(object.token);
          fbb.startTable(6);
          fbb.addInt64(1, object.itemToOne.targetId);
          fbb.addOffset(2, refDataOffset);
          fbb.addOffset(3, tokenOffset);
          fbb.addInt64(4, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final refDataParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final tokenParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object =
              ImageImpl(refData: refDataParam, token: tokenParam, id: idParam);
          object.itemToOne.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.itemToOne.attach(store);
          return object;
        }),
    ContainmentImpl: obx_int.EntityDefinition<ContainmentImpl>(
        model: _entities[6],
        toOneRelations: (ContainmentImpl object) => [],
        toManyRelations: (ContainmentImpl object) => {},
        getId: (ContainmentImpl object) => object.id,
        setId: (ContainmentImpl object, int id) {
          object.id = id;
        },
        objectToFB: (ContainmentImpl object, fb.Builder fbb) {
          fbb.startTable(2);
          fbb.addInt64(0, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = ContainmentImpl(id: idParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ContainerImpl] entity fields to define ObjectBox queries.
class ContainerImpl_ {
  /// See [ContainerImpl.id].
  static final id =
      obx.QueryIntegerProperty<ContainerImpl>(_entities[0].properties[0]);

  /// See [ContainerImpl.containerKey].
  static final containerKey =
      obx.QueryRelationToOne<ContainerImpl, ContainerKey>(
          _entities[0].properties[1]);
}

/// [ContainerKey] entity fields to define ObjectBox queries.
class ContainerKey_ {
  /// See [ContainerKey.number].
  static final number =
      obx.QueryIntegerProperty<ContainerKey>(_entities[1].properties[0]);

  /// See [ContainerKey.id].
  static final id =
      obx.QueryIntegerProperty<ContainerKey>(_entities[1].properties[1]);

  /// See [ContainerKey.refValue].
  static final refValue =
      obx.QueryStringProperty<ContainerKey>(_entities[1].properties[2]);

  /// See [ContainerKey.kindValue].
  static final kindValue =
      obx.QueryIntegerProperty<ContainerKey>(_entities[1].properties[3]);

  /// See [ContainerKey.sizeValue].
  static final sizeValue =
      obx.QueryIntegerProperty<ContainerKey>(_entities[1].properties[4]);
}

/// [ItemImpl] entity fields to define ObjectBox queries.
class ItemImpl_ {
  /// See [ItemImpl.id].
  static final id =
      obx.QueryIntegerProperty<ItemImpl>(_entities[2].properties[0]);

  /// See [ItemImpl.key].
  static final key =
      obx.QueryRelationToOne<ItemImpl, ItemKey>(_entities[2].properties[1]);

  /// See [ItemImpl.imageToOne].
  static final imageToOne =
      obx.QueryRelationToOne<ItemImpl, ImageImpl>(_entities[2].properties[2]);
}

/// [ItemKey] entity fields to define ObjectBox queries.
class ItemKey_ {
  /// See [ItemKey.id].
  static final id =
      obx.QueryIntegerProperty<ItemKey>(_entities[3].properties[0]);

  /// See [ItemKey.refData].
  static final refData =
      obx.QueryStringProperty<ItemKey>(_entities[3].properties[1]);
}

/// [ContainerAllocationImpl] entity fields to define ObjectBox queries.
class ContainerAllocationImpl_ {
  /// See [ContainerAllocationImpl.id].
  static final id = obx.QueryIntegerProperty<ContainerAllocationImpl>(
      _entities[4].properties[0]);

  /// See [ContainerAllocationImpl.start].
  static final start = obx.QueryIntegerProperty<ContainerAllocationImpl>(
      _entities[4].properties[1]);

  /// See [ContainerAllocationImpl.fixedDisplayLength].
  static final fixedDisplayLength =
      obx.QueryIntegerProperty<ContainerAllocationImpl>(
          _entities[4].properties[2]);

  /// See [ContainerAllocationImpl.containerTypeUid].
  static final containerTypeUid =
      obx.QueryIntegerProperty<ContainerAllocationImpl>(
          _entities[4].properties[3]);

  /// See [ContainerAllocationImpl.uid].
  static final uid = obx.QueryStringProperty<ContainerAllocationImpl>(
      _entities[4].properties[4]);
}

/// [ImageImpl] entity fields to define ObjectBox queries.
class ImageImpl_ {
  /// See [ImageImpl.itemToOne].
  static final itemToOne =
      obx.QueryRelationToOne<ImageImpl, ItemImpl>(_entities[5].properties[0]);

  /// See [ImageImpl.refData].
  static final refData =
      obx.QueryStringProperty<ImageImpl>(_entities[5].properties[1]);

  /// See [ImageImpl.token].
  static final token =
      obx.QueryStringProperty<ImageImpl>(_entities[5].properties[2]);

  /// See [ImageImpl.id].
  static final id =
      obx.QueryIntegerProperty<ImageImpl>(_entities[5].properties[3]);
}

/// [ContainmentImpl] entity fields to define ObjectBox queries.
class ContainmentImpl_ {
  /// See [ContainmentImpl.id].
  static final id =
      obx.QueryIntegerProperty<ContainmentImpl>(_entities[6].properties[0]);
}
